// LuxStudio/portal/src/views/Register.vue
<template>
  <div class="max-w-md mx-auto p-6 bg-gray-800 text-white rounded shadow">
    <h1 class="text-2xl font-bold mb-6 text-center">Register</h1>
    <form @submit.prevent="handleRegister">
      <div class="mb-4">
        <label for="username" class="block mb-2 text-sm font-medium">Username</label>
        <input
          type="text"
          id="username"
          v-model="username"
          class="w-full p-2 border border-gray-600 rounded bg-gray-700 text-white"
          placeholder="Enter your username"
          required
        />
      </div>
      <div class="mb-4">
        <label for="email" class="block mb-2 text-sm font-medium">Email</label>
        <input
          type="email"
          id="email"
          v-model="email"
          class="w-full p-2 border border-gray-600 rounded bg-gray-700 text-white"
          placeholder="Enter your email"
          required
        />
      </div>
      <div class="mb-4">
        <label for="password" class="block mb-2 text-sm font-medium">Password</label>
        <input
          type="password"
          id="password"
          v-model="password"
          class="w-full p-2 border border-gray-600 rounded bg-gray-700 text-white"
          placeholder="Enter your password"
          required
        />
      </div>
      <div class="mb-4">
        <label for="avatar" class="block mb-2 text-sm font-medium">Avatar (optionnel)</label>
        <input
          type="file"
          id="avatar"
          @change="handleAvatarChange"
          accept="image/png, image/jpeg"
          class="w-full p-2 border border-gray-600 rounded bg-gray-700 text-white"
        />
      </div>
      <div v-if="avatarPreviewUrl" class="mb-4">
        <label class="block mb-2 text-sm font-medium">Aperçu de l’avatar</label>
        <img
          :src="avatarPreviewUrl"
          alt="Aperçu de l’avatar"
          class="w-24 h-24 rounded-full border border-gray-600 object-cover"
        />
      </div>
      <button type="submit" class="w-full bg-blue-600 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded">
        Register
      </button>
      <p v-if="errorMessage" class="text-red-500 mt-4 text-sm">{{ errorMessage }}</p>

      <!-- Redirect to login -->
      <p class="text-sm text-gray-300 mt-4 text-center">
        Already have an account?
        <router-link to="/" class="text-blue-400 hover:underline">Log in.</router-link>
      </p>
    </form>
  </div>
</template>

<script>
import { AuthService } from "../services/auth_services";

export default {
  data() {
    return {
      username: "",
      email: "",
      password: "",
      errorMessage: "",
      avatarFile: null,
      avatarPreviewUrl: null,
    };
  },
  methods: {
    async handleRegister() {
      const authService = new AuthService();

      try {
        await authService.register(this.username, this.email, this.password);
        const token = await authService.loginAndGetToken(this.username, this.password);

        if (this.avatarFile) {
          const formData = new FormData();
          formData.append("file", this.avatarFile);

          await fetch("http://localhost:5269/auth/upload-avatar", {
            method: "POST",
            headers: { Authorization: `Bearer ${token}` },
            body: formData,
          });
        }

        alert("Account created!");
        this.$router.push("/");
      } catch (error) {
        this.errorMessage = error.message || "Registration failed.";
      }
    },

    handleAvatarChange(event) {
      const file = event.target.files[0];
      this.avatarFile = file;

      if (this.avatarPreviewUrl) {
        URL.revokeObjectURL(this.avatarPreviewUrl);
      }

      if (file) {
        this.avatarPreviewUrl = URL.createObjectURL(file);
      }
    },
  },
  beforeUnmount() {
    if (this.avatarPreviewUrl) {
      URL.revokeObjectURL(this.avatarPreviewUrl);
    }
  },
};
</script>

<style scoped>
/* Styles similar to Login.vue */
</style>

// LuxStudio/portalv2/src/app/(auth)/register/page.tsx
'use client'

import { useState, useRef, useEffect } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { Logo } from '@/app/logo'
import { Button } from '@/components/button'
import { Field, Label } from '@/components/fieldset'
import { Heading } from '@/components/heading'
import { Input } from '@/components/input'
import { Strong, Text, TextLink } from '@/components/text'
import { AuthService } from '@/services/auth'

export default function Register() {
  const router = useRouter()
  const searchParams = useSearchParams()

  const [step, setStep] = useState<'form' | 'code'>('form')
  const [username, setUsername] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [avatarFile, setAvatarFile] = useState<File | null>(null)
  const [avatarPreviewUrl, setAvatarPreviewUrl] = useState<string | null>(null)
  const [verificationCode, setVerificationCode] = useState('')
  const [errorMessage, setErrorMessage] = useState('')
  const [successMessage, setSuccessMessage] = useState('')
  const [isSubmitting, setIsSubmitting] = useState(false)

  const fileInputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    const queryEmail = searchParams.get('email')
    if (searchParams.get('prefilled') === 'true' && queryEmail) {
      setEmail(queryEmail)
    }
  }, [searchParams])

  useEffect(() => {
    return () => {
      if (avatarPreviewUrl) URL.revokeObjectURL(avatarPreviewUrl)
    }
  }, [avatarPreviewUrl])

  const handleAvatarChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    setAvatarFile(file)
    const preview = URL.createObjectURL(file)
    setAvatarPreviewUrl(preview)
  }

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault()
    if (isSubmitting) return
    setIsSubmitting(true)
    setErrorMessage('')
    try {
      await AuthService.requestVerification(username, email, password)
      setStep('code')
    } catch (err: any) {
      setErrorMessage(err.message || 'Unexpected error')
    } finally {
      setIsSubmitting(false)
    }
  }

  const verifyCode = async (e: React.FormEvent) => {
    e.preventDefault()
    if (isSubmitting) return
    setIsSubmitting(true)
    setErrorMessage('')
    try {
      if (verificationCode.length !== 6) throw new Error('Code must be 6 digits')

      await AuthService.verifyCode(email, verificationCode)

      const token = await AuthService.login(email, password, '') // Pas de captcha ici
      localStorage.setItem('token', token)

      if (avatarFile) {
        await AuthService.uploadAvatar(avatarFile, token)
      }

      router.push('/dashboard')
    } catch (err: any) {
      setErrorMessage(err.message || 'Error during verification')
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <form onSubmit={step === 'form' ? handleRegister : verifyCode} className="grid w-full max-w-sm grid-cols-1 gap-8">
      <Logo className="h-6 text-zinc-950 dark:text-white forced-colors:text-[CanvasText]" />
      <Heading>{step === 'form' ? 'Create your account' : 'Enter verification code'}</Heading>

      {step === 'form' && (
        <>
          <Field>
            <Label>Username</Label>
            <Input value={username} onChange={(e) => setUsername(e.target.value)} required />
          </Field>
          <Field>
            <Label>Email</Label>
            <Input value={email} onChange={(e) => setEmail(e.target.value)} required />
          </Field>
          <Field>
            <Label>Password</Label>
            <Input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required />
          </Field>
          <Field>
            <Label>Avatar (optional)</Label>
            <Input type="file" ref={fileInputRef} onChange={handleAvatarChange} accept="image/png, image/jpeg" />
          </Field>
          {avatarPreviewUrl && (
            <img src={avatarPreviewUrl} alt="Avatar preview" className="w-20 h-20 rounded-full object-cover border" />
          )}
        </>
      )}

      {step === 'code' && (
        <Field>
          <Label>Verification Code</Label>
          <Input
            value={verificationCode}
            onChange={(e) => setVerificationCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
            required
            maxLength={6}
          />
        </Field>
      )}

      {errorMessage && <Text className="text-red-500 text-sm">{errorMessage}</Text>}
      {successMessage && <Text className="text-green-500 text-sm">{successMessage}</Text>}

      <Button type="submit" className="w-full" disabled={isSubmitting}>
        {isSubmitting ? 'Please wait...' : step === 'form' ? 'Register' : 'Confirm Code'}
      </Button>

      <Text>
        Already have an account?{' '}
        <TextLink href="/login">
          <Strong>Log in</Strong>
        </TextLink>
      </Text>
    </form>
  )
}
