// LuxStudio/portal/src/views/Login.vue
<template>
  <div class="max-w-md mx-auto p-6 bg-gray-800 text-white rounded-lg shadow-lg">
    <h1 class="text-2xl font-bold mb-6 text-center">Login</h1>
    <form @submit.prevent="handleLogin" class="space-y-4">
      <div>
        <label for="username" class="block text-sm font-medium mb-2">Username</label>
        <input 
          type="text" 
          id="username" 
          v-model="username" 
          class="w-full p-3 border border-gray-600 rounded bg-gray-700 text-white focus:ring focus:ring-blue-500"
          placeholder="Enter your username" 
          required
        />
      </div>
      <div>
        <label for="password" class="block text-sm font-medium mb-2">Password</label>
        <input 
          type="password" 
          id="password" 
          v-model="password" 
          class="w-full p-3 border border-gray-600 rounded bg-gray-700 text-white focus:ring focus:ring-blue-500"
          placeholder="Enter your password" 
          required
        />
      </div>

      <!-- hCaptcha Widget -->
      <div>
        <div ref="hcaptcha" class="h-captcha"></div>
      </div>

      <button 
        type="submit" 
        class="w-full bg-blue-600 hover:bg-blue-500 text-white font-bold py-3 px-4 rounded transition duration-300 disabled:opacity-50" 
        :disabled="!captchaToken"
      >
        Login
      </button>

      <p v-if="errorMessage" class="text-red-500 mt-4 text-sm">{{ errorMessage }}</p>

      <!-- Redirect to register -->
      <p class="text-sm text-gray-300 mt-4 text-center">
        No account?
        <router-link to="/register" class="text-blue-400 hover:underline">Sign up here.</router-link>
      </p>
    </form>
  </div>
</template>

<script>
import { AuthService } from '../services/auth_services';

export default {
  data() {
    return {
      username: '',
      password: '',
      captchaToken: '',
      errorMessage: '',
    };
  },
  mounted() {
    this.$nextTick(() => {
      if (window.hcaptcha) {
        window.hcaptcha.render(this.$refs.hcaptcha, {
          sitekey: "3406257c-d7d0-4ca2-93ec-dc3cf6346ac4",
          callback: (token) => {
            this.captchaToken = token;
          }
        });
      }
    });
  },
  methods: {
    async handleLogin() {
      const authService = new AuthService();
      try {
        const token = await authService.login(
          this.username,
          this.password,
          this.captchaToken
        );
        localStorage.setItem('token', token);
        const redirect = this.$route.query.redirect || '/dashboard';
        this.$router.push(redirect);
      } catch (error) {
        this.errorMessage = error.message || 'An unexpected error occurred.';
      }
    },
  },
};
</script>

// LuxStudio/portalv2/src/app/(auth)/login/page.tsx
'use client'

import { useRef, useState, useEffect } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { Button } from '@/components/button'
import { Checkbox, CheckboxField } from '@/components/checkbox'
import { Field, Label } from '@/components/fieldset'
import { Heading } from '@/components/heading'
import { Input } from '@/components/input'
import { Strong, Text, TextLink } from '@/components/text'
import { Logo } from '@/app/logo'
import { AuthService } from '@/services/auth'

export default function LoginPage() {
  const router = useRouter()
  const searchParams = useSearchParams()

  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [captchaToken, setCaptchaToken] = useState('')
  const [errorMessage, setErrorMessage] = useState('')
  const [isLoading, setIsLoading] = useState(false)

  const captchaRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (window.hcaptcha && captchaRef.current) {
      window.hcaptcha.render(captchaRef.current, {
        sitekey: '3406257c-d7d0-4ca2-93ec-dc3cf6346ac4',
        callback: (token: string) => setCaptchaToken(token),
      })
    }
  }, [])

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault()
    setErrorMessage('')
    setIsLoading(true)

    try {
      const token = await AuthService.login(username, password, captchaToken)
      localStorage.setItem('token', token)
      router.push('/')
    } catch (error: any) {
      setErrorMessage(error.message || 'An unexpected error occurred.')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="flex min-h-screen flex-col items-center justify-center px-4 sm:px-6 lg:px-8">
      <div className="w-full max-w-sm space-y-8">
        <div className="flex justify-center">
          <Logo className="h-6 text-zinc-950 dark:text-white forced-colors:text-[CanvasText]" />
        </div>
        <Heading level={1} className="text-center">
          Sign in to your account
        </Heading>
        <form onSubmit={handleLogin} className="space-y-6">
          <Field>
            <Label>Email</Label>
            <Input
              type="email"
              name="email"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
            />
          </Field>
          <Field>
            <Label>Password</Label>
            <Input
              type="password"
              name="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
            />
          </Field>
          <div ref={captchaRef} className="h-captcha"></div>
          <div className="flex items-center justify-between">
            <CheckboxField>
              <Checkbox name="remember" />
              <Label>Remember me</Label>
            </CheckboxField>
            <Text>
              <TextLink href="/forgot-password">
                <Strong>Forgot password?</Strong>
              </TextLink>
            </Text>
          </div>
          <Button type="submit" className="w-full" disabled={!captchaToken || isLoading}>
            {isLoading ? 'Logging in...' : 'Login'}
          </Button>
          {errorMessage && (
            <Text className="text-sm text-red-500">{errorMessage}</Text>
          )}
          <Text className="text-center">
            Don’t have an account?{' '}
            <TextLink href="/register">
              <Strong>Sign up</Strong>
            </TextLink>
          </Text>
        </form>
      </div>
    </div>
  )
}
